# Site
name: "Dan's IT Cookbook"
description: 'recipes for IT tasks'
logo: 'assets/images/cookbook-logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
url: 'https://www.dans-it-cookbook.com'
# disqus: 'demowebsite'
email: 'dan@dans-it-coobook.com'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    dan:
      name:           Dan
      site:           https://www.reserchonknowing.com
      avatar:         assets/images/dan.jpg
      bio:            "Hi, I am Dan! I hope you enjoy thes recipes to perform IT tasks."
      email:          dan@dans-it-cookbook.com
      twitter:        https://twitter.com/Dan_IT_Cookbook

 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: dan
      avatar: assets/images/dan.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]